# fly.toml app configuration file for KKH Nursing Chatbot
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kkh-nursing-chatbot'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8501'
  RENDER = 'false'
  STREAMLIT_SERVER_HEADLESS = 'true'
  STREAMLIT_SERVER_ENABLE_CORS = 'false'
  STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION = 'false'

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '15s'
    method = 'GET'
    path = '/_stcore/health'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
