# fly.toml app configuration file generated for kkh-nursing-chatbot-spring-river-7190 on 2025-07-22T23:28:41+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kkh-nursing-chatbot-spring-river-7190'
primary_region = 'sin'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]

[env]
  PORT = '8501'

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8501

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.tcp_checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
