# fly.toml app configuration file generated for kkh-nursing-chatbot on 2025-07-24T10:08:57+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kkh-nursing-chatbot'
primary_region = 'sin'

[build]

[env]
  PORT = '8501'
  RENDER = 'false'

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/_stcore/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
